services:
  - type: web
    name: TinyStatus Service
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    region: frankfurt
    envVars:
      - key: CHECK_INTERVAL
        value: "30"
      - key: MAX_HISTORY_ENTRIES
        value: "100"
      - key: LOG_LEVEL
        value: "INFO"
      - key: CHECKS_FILE
        value: "checks.yaml"
      - key: INCIDENTS_FILE
        value: "incidents.md"
      - key: TEMPLATE_FILE
        value: "index.html.theme"
      - key: HISTORY_TEMPLATE_FILE
        value: "history.html.theme"
      - key: STATUS_HISTORY_FILE
        value: "history.json"
